---
Name: RestfulApiConfig
---
ApiController:
  underscoreFields: true
  useAccesstokenAuth: true
  accessTokenPropertyName: 'X-Accesstoken'
  allowOverrideConfiguration: false
AuthSession:
  validInMinutesFromNow: 10080
  adminAccessToken: null
  requiredGroup: null
  requiredPermission: null
  urlSegment: 'auth'
DataObject:
  jsonDateFormat: 'D M d Y H:i:s O'
  underscoreFields: true
  castDataObjectFields: true
  extensions:
    - ApiDataObject
---
Except:
  environment: 'live'
---
ApiController:
  allowOverrideConfiguration: true
AuthSession:
  adminAccessToken: 84c44b7ee63a9919aa272673eecfc7f9b7424e47
